### ISSUE TITLE
qrcode dont work

### ISSUE THREAD

**Issue by deividnn** [anastaciocintra/escpos-coffee-samples#3]
QRCode qrcode = new QRCode();

            escpos.writeLF("QRCode default options");
            escpos.feed(2);
            escpos.write(qrcode, "hello qrcode");
            escpos.feed(3);

this code print : **010hello qrcode0**

**Comment by anastaciocintra** [comment]
Hi @deividnn,
maybe your printer isn't compatible with qrcode methods of this library.


but you need to test it..


[here](https://github.com/anastaciocintra/escpos-coffee-samples/tree/master/usual) is an sample of how to use barcode and qrcode... 
```
mvn clean package
java -jar barcode/target/barcode-4.0.1-jar-with-dependencies.jar your_printer_name
```
this application should output some barcode, qrcode and pdf417...
I hope this test works.

**Comment by deividnn** [comment]
nao deu certo com a bematech MP-4200 TH..so qrcode q nao funciona
![IMG_20200218_114717205](https://user-images.githubusercontent.com/6463635/74746681-90464700-5244-11ea-851e-350ff657c2d7.jpg)

**Comment by deividnn** [comment]
atualizei o firmware da impressora e deu certo..muito obrigado

**Comment by anastaciocintra** [comment]
viva!
obrigado pelo retorno,
qualquer coisa é só chamar
grande abraço.
Marco
