### ISSUE TITLE
BufferedImage doesn't exists on Android

### ISSUE THREAD

**Issue by sfabio01** [anastaciocintra/escpos-coffee-samples#9]
I'm not able to print a PDF from my Android app because BufferedImage class is not defined in Android

**Comment by anastaciocintra** [comment]
Are you saying about the code pdf printing on escpos-samples?

https://github.com/anastaciocintra/escpos-coffee-samples/tree/master/miscellaneous/PdfPrinting

**Comment by sfabio01** [comment]
Exactly, I was trying to convert a pdf to image in my android app but seems
like the package that contains the BufferedImage class doesn't exists
because Android uses its own packages for image rendering.
Actually I don't need it anymore but I hope I've been helpful presenting
the issue.

Il dom 15 nov 2020, 12:56 PM Marco Antonio Anastacio Cintra <
notifications@github.com> ha scritto:

**Comment by anastaciocintra** [comment]
Hi @sfabio01 
I've wrote one sample (just now) using PdfRenderer (android lib)

its on https://github.com/anastaciocintra/escpos-coffee-samples/tree/master/miscellaneous/pdfprintingandroid

 see you.
